#!/usr/bin/env python3
"""Build Persian HTML from the English source. Fail on untranslated copy.
Run from any directory with Python 3; no third-party dependencies required.
"""
from html import escape
from html.parser import HTMLParser
from pathlib import Path
import argparse
import json
import re

ROOT = Path(__file__).resolve().parents[1]
COPY = json.loads((ROOT / 'locales/fa.json').read_text())

class PersianPage(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts = []

    def handle_decl(self, decl):
        self.parts.append('<!' + decl + '>')

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        for key in ('alt', 'aria-label', 'placeholder'):
            if a.get(key):
                a[key] = COPY['attributes'][a[key]]
        if tag == 'html':
            a.update(lang='fa', dir='rtl')
        if tag == 'meta':
            kind = a.get('name', a.get('property'))
            if kind in ('description', 'og:title', 'og:description'):
                a['content'] = COPY['attributes'][a['content']]
            elif kind == 'og:url':
                a['content'] = 'https://erfanzn.github.io/fa/'
            elif kind == 'og:locale':
                a['content'] = 'fa_IR'
        if tag == 'link' and a.get('rel') == 'canonical':
            a['href'] = 'https://erfanzn.github.io/fa/'
        if tag == 'link' and a.get('rel') == 'preload':
            a['href'] = '/assets/vazirmatn.woff2'
        if 'language-switch' in a.get('class', '').split():
            a.update(href='/', lang='en', dir='ltr', hreflang='en')
        if 'wordmark' in a.get('class', '').split():
            a.update(lang='en', dir='ltr')
        if tag == 'a' and a.get('href', '').startswith('mailto:'):
            a['dir'] = 'ltr'
        if tag in ('input', 'textarea') and a.get('name') in ('name', 'message', 'email'):
            a['dir'] = 'ltr' if a['name'] == 'email' else 'auto'
        if tag == 'text' and a.get('x') in ('60', '500'):
            a['x'] = '500' if a['x'] == '60' else '60'
        if a.get('class') == 'clear-path':
            a['d'] = 'M500 140 H60'
        if tag == 'script' and a.get('src') == '/app.js':
            self.parts.append('<script defer src="/fa-i18n.js"></script>')
        self.parts.append('<' + tag + ''.join(' ' + k + ('="' + escape(v, quote=True) + '"' if v is not None else '') for k, v in a.items()) + '>')
        if tag == 'link' and a.get('href', '').split('?', 1)[0] == '/styles.css':
            self.parts.append('<link rel="stylesheet" href="/fa.css?v=20260925-2">')

    def handle_endtag(self, tag):
        self.parts.append('</' + tag + '>')

    def handle_data(self, data):
        key = data.strip()
        if key:
            translated = COPY['text'][key]
            data = re.match(r'^\s*', data)[0] + translated + re.search(r'\s*$', data)[0]
        self.parts.append(escape(data, quote=False))

    def handle_comment(self, data):
        self.parts.append('<!--' + data + '-->')

page = PersianPage()
page.feed((ROOT / 'dist/index.html').read_text())
outputs = {
    ROOT / 'dist/fa/index.html': ''.join(page.parts),
    ROOT / 'dist/fa-i18n.js': '// Generated by scripts/build-locales.py. Edit locales/fa.json.\n' +
        '(() => {\n  const copy = ' + json.dumps(COPY['dynamic'], ensure_ascii=False, indent=2) + ';\n' +
        "  window.portfolioTranslate = (text, values = {}) => (copy[text] || text).replace(/\\{(\\w+)\\}/g, (_, key) => typeof values[key] === 'number' ? values[key].toLocaleString('fa-IR') : (values[key] ?? ''));\n})();\n"
}
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for path, content in outputs.items():
    if args.check:
        assert path.exists() and path.read_text() == content, f'Regenerate {path.relative_to(ROOT)}'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
print('Persian page and interface messages are complete and in sync.')
